title: Goal-driven Exploration for Android Apps
description: GoalExplorer: performing goal-driven exploration to trigger functionality of interest for Android apps.
show_downloads: true
theme: jekyll-theme-leap-day
