title: Goal-driven Exploration for Android Apps
description: GoalExplorer: performing goal-driven exploration to trigger functionality of interest for Android apps.
show_downloads: true
theme: jekyll-theme-leap-day
github:
  zip_url: https://drive.google.com/open?id=1w6MXs5gPbX-lpl2SE1jYz_Xo1A40rY13
  tar_url: https://drive.google.com/open?id=1FGZcDU9zI4BrqHOwtBDRJi_Nqgr3H8PD
